### ISSUE TITLE
Refactor tests to use ex_machina factory

### ISSUE THREAD

**Issue by AndrewDryga** [edenlabllc/prm.api#22]

**Comment by gmile** [comment]
This time I'd try something different, and go with homebrew factories. Reason: in it's current state `ex_machine` is the same as just creating your own records.

I see some some fundamental limitations in it's current state:

1. it won't run factories through changesets:
    * it means ex_machine gives you a tool to create _possibly_ invalid records in DB (as records won't go thorough normal validation when going through normal changesets). This is considered a [bad practice](https://robots.thoughtbot.com/testing-your-factories-first) (the article is from thoughtbot, the creator of ex_machina); it is recommended that you test your factories anyway,
    * this fact contributes to speeding up DB records creation, however the speed is so negligible it can hardly serve as a criteria for tool choice here (especially at current scale of the app).

2. ex_machina currently does not support the most, in my opinion, useful feature of it's ruby ancestor, FactoryGirl – lazy attributes (it's explicitly [not planned](https://github.com/thoughtbot/ex_machina/pull/131#issuecomment-282507691) either):

    * if you have a field a value of which you'd like to determine based on another field – it would help significantly increase the quality of generated records – you can't do that with current ex_machine,

      This is useful when, say, you have a record with fields `my_value = 100` and `my_booked_value = 100`, for such record you'd want to always have a `status = "sold"`

    * if you have a `Comment` factory such that depends on `Post` factory, and you'd like at runtime create a comment with a slightly different `Post`, e.g.:

      ```elixir
      insert(:comment) # vs
      insert(:comment, post: my_custom_post)
      ```

      You'll end up creating a comment and two posts (one connected to comment, another one – orphaned).

The biggest value of keeping factories is – having one place to change the record in tests. You add a field to DB, factory becomes invalid and tests start to fail. Then you make a change in a single place, e.g. add an attribute to a single factory – and all tests are green again. This is really good pattern.

I believe we can do housekeeping of our own having all of our fixtures kept and managed in a single file, pretty much following the same pattern.

That said, FWIW, I'm :-1: on adding `ex_machina`.

**Comment by gmile** [comment]
We ended up using `ex_machina`, and so far I'm happy with it.
