### ISSUE TITLE
[INTERNAL.API] Get Global Parameters 

### ISSUE THREAD

**Issue by mmiliaieva** [edenlabllc/prm.api#71]
Implement the subj. service according to the [spec](http://docs.ehealthapi1.apiary.io/#reference/internal.-global-parameters-and-products/global-parameters/get-global-parameters)

**Comment by DPashchenko** [comment]
Add table in PRM db: [global_parameters](https://github.com/Nebo15/ehealth.api/blob/master/specs/database_schema/prm.erd)
Add CRUD operations according to specified table. 
[GET](http://docs.ehealthapi1.apiary.io/#reference/internal.-global-parameters-and-products/global-parameters/get-global-parameters)
[PUT](http://docs.ehealthapi1.apiary.io/#reference/internal.-global-parameters-and-products/global-parameters/put-global-parameters)

**Comment by mmiliaieva** [comment]
@DPashchenko close, if everything is OK
